sudo: false
language: node_js
node_js: stable
after_success:
- |2

  $(npm bin)/set-up-ssh --key "$encrypted_52ecd545ca97_key" \
                       --iv "$encrypted_52ecd545ca97_iv" \
                       --path-encrypted-key ".travis/github_deploy_key.enc"

  $(npm bin)/update-branch --commands "yarn run build" \
                           --commit-message "Update website [skip ci]" \
                           --directory "./dist" \
                           --distribution-branch "gh-pages" \
                           --source-branch "master"
